In [10]:
import pandas as pd
import numpy as np
import os
import string
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter
from matplotlib.ticker import StrMethodFormatter
%matplotlib inline

In [14]:


array1 = [
    ["Sector"] * 1 + ["Mobile Combustion"] * 12 + ["Electricity Consumption"] * 6 + ["Solid Waste Landfills"] * 6 + ["Stationary Combustion"] * 15 + ["Agriculture & Land management"] * 9+["Wastewater treatment"] * 3 +["Forestry"]*9, ["Subsector"]*1+["Automobile"]*3 + ["Motorcycle"]*3 + ["Trucks"]*3+ ["Buses"]*3 +["Residential"]*3 + 
    ["Commercial/Industrial"]*3 +["Landfill fuel combustion"]*3+["Landfill methane"]*3  +["Residential"]*9+["Commercial"]*3 + ["Industrial"]*3 +["Organic fertilizer"] * 3+ ["Synthetic fertilizer"] * 3+ ["Manure fertilizer"] * 3 + ["Wastewater facility"] * 3 +["Deciduous forest"]*3 +["Coniferous forest"]*3+["Forested wetland"]*3, ["Category"] * 1 + ["Gasoline"] * 6 + ['Diesel']*6 + ["Electricity"] * 6+["Landfill fuel combustion"]*3+["Landfill methane"]*3+["fuel oil"] * 3+ ["natural gas"]*3+["propane"]*3+ ["Distillate Fuel Oil No. 2, Natural Gas, Propane"] * 3 + [' ']*3
    + ["Organic"] * 3+ ["Synthetic"] * 3+ ["Manure"] * 3 + [" "] * 12, ["MSA"] * 1 + ["New Haven-Milford", "Hartford-east Hartford-Middletown", "Bridgeport-Stamford-Norwalk"] * 20,
    ["County"] * 1 + ["New Haven", "Hartford, Middlesex, Tolland", "Fairfield"] * 20, ["Year"] * 1 + ["2021"]*24 +["2020"]*15+["2017"]*9+["2021"]*3+["2015"]*9]

# Create MultiIndex directly
index = pd.MultiIndex.from_arrays(array1)
# Create a Series
emissions = pd.Series(index=index)
# Convert to DataFrame
emissions_df = emissions.to_frame()
Emissions_summary = emissions_df
Emissions_summary = Emissions_summary.iloc[:, :-1]
Emissions_summary

Empty DataFrame
Columns: []
Index: [(Sector, Subsector, Category, MSA, County, Year), (Mobile Combustion, Automobile, Gasoline, New Haven-Milford, New Haven, 2021), (Mobile Combustion, Automobile, Gasoline, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Mobile Combustion, Automobile, Gasoline, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Mobile Combustion, Motorcycle, Gasoline, New Haven-Milford, New Haven, 2021), (Mobile Combustion, Motorcycle, Gasoline, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Mobile Combustion, Motorcycle, Gasoline, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Mobile Combustion, Trucks, Diesel, New Haven-Milford, New Haven, 2021), (Mobile Combustion, Trucks, Diesel, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Mobile Combustion, Trucks, Diesel, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Mobile Combustion, Buses, Diesel, New Haven-Milford, New Haven, 2021), (Mobile Combustion, Buses, Diesel, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Mobile Combustion, Buses, Diesel, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Electricity Consumption, Residential, Electricity, New Haven-Milford, New Haven, 2021), (Electricity Consumption, Residential, Electricity, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Electricity Consumption, Residential, Electricity, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Electricity Consumption, Commercial/Industrial, Electricity, New Haven-Milford, New Haven, 2021), (Electricity Consumption, Commercial/Industrial, Electricity, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Electricity Consumption, Commercial/Industrial, Electricity, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Solid Waste Landfills, Landfill fuel combustion, Landfill fuel combustion, New Haven-Milford, New Haven, 2021), (Solid Waste Landfills, Landfill fuel combustion, Landfill fuel combustion, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Solid Waste Landfills, Landfill fuel combustion, Landfill fuel combustion, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Solid Waste Landfills, Landfill methane, Landfill methane, New Haven-Milford, New Haven, 2021), (Solid Waste Landfills, Landfill methane, Landfill methane, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Solid Waste Landfills, Landfill methane, Landfill methane, Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Stationary Combustion, Residential, fuel oil, New Haven-Milford, New Haven, 2020), (Stationary Combustion, Residential, fuel oil, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2020), (Stationary Combustion, Residential, fuel oil, Bridgeport-Stamford-Norwalk, Fairfield, 2020), (Stationary Combustion, Residential, natural gas, New Haven-Milford, New Haven, 2020), (Stationary Combustion, Residential, natural gas, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2020), (Stationary Combustion, Residential, natural gas, Bridgeport-Stamford-Norwalk, Fairfield, 2020), (Stationary Combustion, Residential, propane, New Haven-Milford, New Haven, 2020), (Stationary Combustion, Residential, propane, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2020), (Stationary Combustion, Residential, propane, Bridgeport-Stamford-Norwalk, Fairfield, 2020), (Stationary Combustion, Commercial, Distillate Fuel Oil No. 2, Natural Gas, Propane, New Haven-Milford, New Haven, 2020), (Stationary Combustion, Commercial, Distillate Fuel Oil No. 2, Natural Gas, Propane, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2020), (Stationary Combustion, Commercial, Distillate Fuel Oil No. 2, Natural Gas, Propane, Bridgeport-Stamford-Norwalk, Fairfield, 2020), (Stationary Combustion, Industrial,  , New Haven-Milford, New Haven, 2020), (Stationary Combustion, Industrial,  , Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2020), (Stationary Combustion, Industrial,  , Bridgeport-Stamford-Norwalk, Fairfield, 2020), (Agriculture & Land management, Organic fertilizer, Organic, New Haven-Milford, New Haven, 2017), (Agriculture & Land management, Organic fertilizer, Organic, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2017), (Agriculture & Land management, Organic fertilizer, Organic, Bridgeport-Stamford-Norwalk, Fairfield, 2017), (Agriculture & Land management, Synthetic fertilizer, Synthetic, New Haven-Milford, New Haven, 2017), (Agriculture & Land management, Synthetic fertilizer, Synthetic, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2017), (Agriculture & Land management, Synthetic fertilizer, Synthetic, Bridgeport-Stamford-Norwalk, Fairfield, 2017), (Agriculture & Land management, Manure fertilizer, Manure, New Haven-Milford, New Haven, 2017), (Agriculture & Land management, Manure fertilizer, Manure, Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2017), (Agriculture & Land management, Manure fertilizer, Manure, Bridgeport-Stamford-Norwalk, Fairfield, 2017), (Wastewater treatment, Wastewater facility,  , New Haven-Milford, New Haven, 2021), (Wastewater treatment, Wastewater facility,  , Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2021), (Wastewater treatment, Wastewater facility,  , Bridgeport-Stamford-Norwalk, Fairfield, 2021), (Forestry, Deciduous forest,  , New Haven-Milford, New Haven, 2015), (Forestry, Deciduous forest,  , Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2015), (Forestry, Deciduous forest,  , Bridgeport-Stamford-Norwalk, Fairfield, 2015), (Forestry, Coniferous forest,  , New Haven-Milford, New Haven, 2015), (Forestry, Coniferous forest,  , Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2015), (Forestry, Coniferous forest,  , Bridgeport-Stamford-Norwalk, Fairfield, 2015), (Forestry, Forested wetland,  , New Haven-Milford, New Haven, 2015), (Forestry, Forested wetland,  , Hartford-east Hartford-Middletown, Hartford, Middlesex, Tolland, 2015), (Forestry, Forested wetland,  , Bridgeport-Stamford-Norwalk, Fairfield, 2015)]

[61 rows x 0 columns]

In [15]:
#import the mobile emissions data

Mobile_emissions = pd.read_csv('../../../results/mobile-emissions-automated-sheet.csv')

CO2 = pd.read_csv('../../../results/CO2-automated-sheet.csv')
CO2 = CO2['CO2'].tolist()

CH4 = pd.read_csv('../../../results/CH4-automated-sheet.csv')
CH4 = CH4['CH4'].tolist()
CH4

N2O = pd.read_csv('../../../results/N2O-automated-sheet.csv')
N2O = N2O['N2O'].tolist()

Mobile_emi = Mobile_emissions
Mobile_emi.drop(Mobile_emi.columns[0], axis=1, inplace=True)
Mobile_emi

,MSA,GHG Emissions(MMTCO2e),CO2 Emissions(MMTCO2e),CH4 Emissions (TMTCO2e),N2O Emissions(TMTCO2e),emissions per capita (MTCO2e),Gasoline Emissions (MMTCO2e),Diesel Emissions (MMTCO2e),Automobile (MMTCO2e),Motorcycle (MMTCO2e),Buses (MMTCO2e),Trucks (MMTCO2e)
0,New Haven-Milford,2.875389,2.867682,0.661296,7.046291,3.325107,1.059169,1.808563,1.028899,0.036643,0.020234,1.789613
1,Hartford-East Hartford-Middletown,4.355344,4.343670,1.001664,10.672997,3.515527,1.604320,2.739426,1.558471,0.055503,0.030649,2.710721
2,Bridgeport-Stamford-Norwalk,2.968949,2.960991,0.682814,7.275563,3.010054,1.093632,1.867410,1.062378,0.037835,0.020893,1.847843

In [16]:
#import electricity emissions
Electricity_emissions = pd.read_csv('../../../results/electricity-emissions-automated-sheet.csv')
Electricity_emissions.drop(Electricity_emissions.columns[0], axis=1, inplace=True)
Electricity_emissions

,MSA,Residential Electricity Emissions (MMTCO2e),Commercial/Industrial Electricity Emissions (MMTCO2e),Total Emissions (MMTCO2e),Emissions per capita (MTCO2e)
0,New Haven-Milford,0.612048,0.702893,1.314940,1.520600
1,Hartford-east Hartford-Middletown,0.875671,0.914548,1.790219,1.475466
2,Bridgeport-Stamford-Norwalk,0.866170,0.853478,1.719647,1.797955

In [17]:
Solidwaste_emissions = pd.read_csv('../../../results/solidwaste-emissions-automated-sheet.csv')
Solidwaste_emissions.drop(Solidwaste_emissions.columns[0], axis=1, inplace=True)
Solidwaste_emissions

,MSA,GHG Emissions (MMTCO2e),Stationary combustion (MMTCO2e),Landfill methane (MMTCO2e)
0,New Haven-Milford,0.000000,0.000000,0.000000
1,Hartford-east Hartford-Middletown,0.384963,0.000476,0.096186
2,Bridgeport-Stamford-Norwalk,0.296673,0.296673,0.000000

In [18]:
Electricity_emissions['Residential Electricity Emissions (MMTCO2e)'] = Electricity_emissions['Residential Electricity Emissions (MMTCO2e)'].astype(float)
Electricity_emissions['Commercial/Industrial Electricity Emissions (MMTCO2e)']=Electricity_emissions['Commercial/Industrial Electricity Emissions (MMTCO2e)'].astype(float)
Electricity_emissions['Total Emissions (MMTCO2e)']=Electricity_emissions['Total Emissions (MMTCO2e)'].astype(float)
Solidwaste_emissions['Landfill methane (MMTCO2e)'] = Solidwaste_emissions['Landfill methane (MMTCO2e)'].astype(float)
Solidwaste_emissions['GHG Emissions (MMTCO2e)']=Solidwaste_emissions['GHG Emissions (MMTCO2e)'].astype(float)
Solidwaste_emissions['Stationary combustion (MMTCO2e)']=Solidwaste_emissions['Stationary combustion (MMTCO2e)'].astype(float)
Solidwaste_emissions['Stationary combustion (MMTCO2e)']

0    0.000000
1    0.000476
2    0.296673
Name: Stationary combustion (MMTCO2e), dtype: float64

In [20]:
#adding into the residential combustion data
residential_emissions = pd.read_csv('../../../results/residential-energy-emissions-breakdown.csv')
residential_emissions

,Unnamed: 0,GHG emissions (MMTCO2e),CO2 emissions (MMTCO2e),CH4 emissions (MMTCO2e),N2O emissions (MMTCO2e)
0,New Haven-Milford,1.361021,1.358261,0.000832,0.001928
1,Hartford-east Hartford-Middletown,2.064354,2.059985,0.001318,0.003051
2,Bridgeport-Stamford-Norwalk,1.492142,1.489018,0.000942,0.002181

In [30]:
residential_breakdowm = pd.read_csv('../../../results/residential-emissions-breakdown-fuel.csv')
residential_oil = residential_breakdowm.iloc[2,1:][::-1].reset_index(drop=True).astype(float)
residential_propane = residential_breakdowm.iloc[1,1:][::-1].reset_index(drop=True).astype(float)
residential_natural = residential_breakdowm.iloc[0,1:][::-1].reset_index(drop=True).astype(float)
residential_oil

0    0.759970
1    1.180163
2    0.846248
Name: 2, dtype: float64

In [22]:
industrial_emissions = pd.read_csv('../../../results/industrial-emissions-breakdown.csv')
industrial_emissions

                          Unnamed: 0  GHG emissions (MMTCO2e)
0                  New Haven-Milford                 0.339402
1  Hartford-east Hartford-Middletown                 0.347809
2        Bridgeport-Stamford-Norwalk                 0.109909

In [23]:
commercial_emissions = pd.read_csv('../../../results/footprint-commercial-emissions.csv')
commercial_emissions
commercial_emissions

,Unnamed: 0,County,Total Footprint Area (square feet),Ratio,GHG Emissions/MMTCO2e
0,0,New Haven-Milford,4.021517e+06,0.249936,0.955882
1,1,Hartford-East Hartford-Middletown,6.733395e+06,0.418479,1.600473
2,2,Bridgeport-Stamford-Norwalk,3.061254e+06,0.190256,0.727635
3,3,Rest of the state,2.274012e+06,0.141329,0.540514
4,4,Statewide,1.609018e+07,1.000000,3.824505

In [24]:
#emissions breakdown by different gases
mobiles_breakdown = pd.read_csv('../../../results/mobile-emissions-breakdown.csv')
mobiles_breakdown

,Unnamed: 0,MSA,CO2 Emissions (MMTCO2e),CH4 Emissions (MMTCO2e),N2O Emissions (MMTCO2e)
0,0,NH_automobile,1.022483,0.000561,0.005855
1,1,HH_automobile,1.548753,0.000850,0.008868
2,2,BSN_automobile,1.055753,0.000580,0.006045
3,3,NH_motorcycle,0.036643,0.000000,0.000000
4,4,HH_motorcycle,0.055503,0.000000,0.000000
5,5,BSN_motorcycle,0.037835,0.000000,0.000000
6,6,NH_trucks,1.788362,0.000097,0.001154
7,7,HH_trucks,2.708827,0.000147,0.001747
8,8,BSN_trucks,1.846552,0.000100,0.001191
9,9,NH_buses,0.020193,0.000003,0.000038
10,10,HH_buses,0.030586,0.000005,0.000058
11,11,BSN_buses,0.020850,0.000003,0.000039

In [25]:
AG_emissions = pd.read_csv('../../../results/agriculture-emissions.csv')
AG_emissions

,Unnamed: 0,MSA,Manure fertilizer land area (acres),Organic fertilizer land area (acres),Synthetic fertilizer land area (acres),Manure fertilizer,Organic fertilizer,Synthetic fertilizer,Manure fertilizer emissions (MMTCO2e),Organic fertilizer emissions (MMTCO2e),Synthetic fertilizer emissions (MMTCO2e),GHG Emissions (MMTCO2e)
0,0,New Haven-Milford,1125,173,3764,10.378229,11.809963,3472.324723,0.000087,0.000099,0.029055,0.029241
1,1,Hartford-East Hartford-Middletown,8267,592,21497,76.263838,40.413284,19831.180812,0.000638,0.000338,0.165942,0.174026
2,2,Bridgeport-Stamford-Norwalk,288,188,1793,2.656827,12.833948,1654.059041,0.000022,0.000107,0.013841,0.014857

In [26]:
wastewater_emissions = pd.read_csv('../../../results/wastewater-emissions.csv')
wastewater_emissions

   Unnamed: 0                                MSA  GHG Emissions (MMTCO2e)
0           0                  New Haven-Milford                 0.092857
1           1  Hartford-East Hartford-Middletown                 0.227553
2           2        Bridgeport-Stamford-Norwalk                 0.076608

In [27]:
land_emissions = pd.read_csv('../../../results/land-cover-emissions.csv')
land_emissions

,Unnamed: 0,Deciduous forest (hectare),Coniferous forest (hectare),Forested wetland (hectare),Deciduous forest sequestration (MTCO2e),Coniferous forest sequestration (MTCO2e),Forested wetland sequestration (MTCO2e),Total carbon sequestration (MMTCO2e)
0,NHM,66913.05753,5263.04256,4614.51081,5.471258e+05,43034.144666,37731.316723,0.627891
1,HEM,192046.17612,35299.67421,15264.87930,1.570298e+06,288633.669457,124815.829743,1.983747
2,BSN,77905.96410,7405.96953,4850.93655,6.370111e+05,60556.144190,39664.491190,0.737232

In [44]:
Total_emi = pd.Series('Total Emissions (MMTCO2e)')
TOTAL_EM = pd.concat([Total_emi,Mobile_emi["Automobile (MMTCO2e)"], Mobile_emi["Motorcycle (MMTCO2e)"], Mobile_emi["Trucks (MMTCO2e)"], Mobile_emi["Buses (MMTCO2e)"],
                       Electricity_emissions['Residential Electricity Emissions (MMTCO2e)'],Electricity_emissions['Commercial/Industrial Electricity Emissions (MMTCO2e)'],
                       Solidwaste_emissions['Stationary combustion (MMTCO2e)'],Solidwaste_emissions['Landfill methane (MMTCO2e)'], residential_oil, residential_natural,residential_propane,commercial_emissions['GHG Emissions/MMTCO2e'][:3],
                     industrial_emissions['GHG emissions (MMTCO2e)'],AG_emissions['Organic fertilizer emissions (MMTCO2e)'],AG_emissions['Synthetic fertilizer emissions (MMTCO2e)'],AG_emissions['Manure fertilizer emissions (MMTCO2e)'],
                     wastewater_emissions['GHG Emissions (MMTCO2e)'],-land_emissions['Deciduous forest sequestration (MTCO2e)']/1000000,-land_emissions['Coniferous forest sequestration (MTCO2e)']/1000000,-land_emissions['Forested wetland sequestration (MTCO2e)']/1000000], axis=0)

TOTAL_EM=TOTAL_EM.tolist()
T_index = pd.MultiIndex.from_arrays(array1)
TOTAL_EM = pd.Series(TOTAL_EM, index=T_index)
TOTAL_EM

Sector             Subsector          Category  MSA                                County                        Year    Total Emissions (MMTCO2e)
Mobile Combustion  Automobile         Gasoline  New Haven-Milford                  New Haven                     2021                     1.028899
                                                Hartford-east Hartford-Middletown  Hartford, Middlesex, Tolland  2021                     1.558471
                                                Bridgeport-Stamford-Norwalk        Fairfield                     2021                     1.062378
                   Motorcycle         Gasoline  New Haven-Milford                  New Haven                     2021                     0.036643
                                                                                                                                   ...
Forestry           Coniferous forest            Hartford-east Hartford-Middletown  Hartford, Middlesex, Tolland  2015                    -0.288634
                                                Bridgeport-Stamford-Norwalk        Fairfield                     2015                    -0.060556
                   Forested wetland             New Haven-Milford                  New Haven                     2015                    -0.037731
                                                Hartford-east Hartford-Middletown  Hartford, Middlesex, Tolland  2015                    -0.124816
                                                Bridgeport-Stamford-Norwalk        Fairfield                     2015                    -0.039664
Length: 61, dtype: object

In [32]:
breakdown_elec = pd.read_csv('../../../results/emissions-electricity-breakdown.csv')
breakdown_elec

,Unnamed: 0,CH4 Emissions (MMTCO2e)_re,CH4 Emissions (MMTCO2e)_co,CO2 Emissions (MMTCO2e)_re,CO2 Emissions (MMTCO2e)_co,N2O Emissions (MMTCO2e)_re,N2O Emissions (MMTCO2e)_co
0,0,0.002026,0.002326,0.607004,0.697100,0.003018,0.003466
1,1,0.002898,0.003027,0.868454,0.907011,0.004318,0.004510
2,2,0.002867,0.002825,0.859031,0.846444,0.004272,0.004209

In [35]:
breakdown_residential = pd.read_csv('../../../results/residential-emissions-breakdown.csv')
breakdown_residential

,Unnamed: 0,GHG emissions (MMTCO2e),CO2 emissions (MMTCO2e),CH4 emissions (MMTCO2e),N2O emissions (MMTCO2e)
0,New Haven-Milford,1.361021,1.358261,0.000832,0.001928
1,Hartford-east Hartford-Middletown,2.064354,2.059985,0.001318,0.003051
2,Bridgeport-Stamford-Norwalk,1.492142,1.489018,0.000942,0.002181

In [ ]:
co2_emi = pd.Series('CO2 Emissions (MMTCO2e)')
co2_EM = pd.concat([co2_emi,mobiles_breakdown['CO2 Emissions (MMTCO2e)'],breakdown_elec['CO2 Emissions (MMTCO2e)_re'],breakdown_elec['CO2 Emissions (MMTCO2e)_co'], pd.Series([''] *6),breakdown_residential['CO2 emissions (MMTCO2e)'],pd.Series([''] * 27)], axis=0)

#TOTAL_EM=TOTAL_EM.reset_index(drop=True)
co2_EM =co2_EM .tolist()

T_index = pd.MultiIndex.from_arrays(array1)
co2_EM  = pd.Series(co2_EM , index=T_index)


ch4_emi = pd.Series('CH4 Emissions (MMTCO2e)')
ch4_EM = pd.concat([ch4_emi,mobiles_breakdown['CH4 Emissions (MMTCO2e)'],breakdown_elec['CH4 Emissions (MMTCO2e)_re'],breakdown_elec['CH4 Emissions (MMTCO2e)_co'], pd.Series([''] *6),breakdown_residential['CH4 emissions (MMTCO2e)'],pd.Series([''] * 27)], axis=0)


#TOTAL_EM=TOTAL_EM.reset_index(drop=True)
ch4_EM =ch4_EM .tolist()

T_index = pd.MultiIndex.from_arrays(array1)
ch4_EM  = pd.Series(ch4_EM , index=T_index)

n2o_emi = pd.Series('N2O Emissions (MMTCO2e)')
n2o_EM = pd.concat([n2o_emi,mobiles_breakdown['N2O Emissions (MMTCO2e)'],breakdown_elec['N2O Emissions (MMTCO2e)_re'],breakdown_elec['N2O Emissions (MMTCO2e)_co'], pd.Series([''] *6),breakdown_residential['N2O emissions (MMTCO2e)'],pd.Series([''] * 27)], axis=0)


#TOTAL_EM=TOTAL_EM.reset_index(drop=True)
n2o_EM =n2o_EM .tolist()

T_index = pd.MultiIndex.from_arrays(array1)
n2o_EM  = pd.Series(n2o_EM , index=T_index)

In [37]:
population = pd.read_csv('../../../results/population_five_towns.csv')
population = population[['Year', 'New Haven-Milford, CT Metro Area', 'Hartford-East Hartford-Middletown, CT Metro Area', 'Bridgeport-Stamford-Norwalk, CT Metro Area', 'Connecticut']]
population_20 = population.iloc[1,1:4]
population_21 = population.iloc[0,1:4]
population_17 = population.iloc[2,1:4]
population_15 = population.iloc[3,1:4]

popu = pd.Series('Population')
pop = pd.concat([popu,pd.Series(np.tile(population_21, 8)), pd.Series(np.tile(population_20, 5)),pd.Series(np.tile(population_17, 3)),pd.Series(np.tile(population_21, 1)),pd.Series(np.tile(population_15, 3))], axis=0)

#TOTAL_EM=TOTAL_EM.reset_index(drop=True)
pop =pop.tolist()

T_index = pd.MultiIndex.from_arrays(array1)
pop  = pd.Series(pop, index=T_index)

#numeric_pop = pd.to_numeric(pop.str.replace(',', ''), errors='coerce')
population

,Year,"New Haven-Milford, CT Metro Area","Hartford-East Hartford-Middletown, CT Metro Area","Bridgeport-Stamford-Norwalk, CT Metro Area",Connecticut
0,2021,864751,1238888,986344,3605330
1,2020,855733,1231523,972981,3570549
2,2017,862127,1239055,976389,3594478
3,2015,862224,1240217,969332,3593222

In [38]:


emissions_capita = TOTAL_EM[1:]*1000000/pop[1:]
#emissions_capita = TOTAL_EM*1000000/numeric_pop

In [41]:
combined_series = pd.concat([pop, TOTAL_EM, emissions_capita, co2_EM, ch4_EM, n2o_EM], axis=1)
combined_series.iloc[0,2]='Emissions per capita (MTCO2e)'
combined_series

NameError: name 'ch4_EM' is not defined

In [ ]:
combined_series = pd.concat([pop, TOTAL_EM, emissions_capita, co2_EM, ch4_EM, n2o_EM], axis=1)
combined_series.iloc[0,2]='Emissions per capita (MTCO2e)'
combined_series

In [67]:
# Reset the index, moving it inside the DataFrame and adding a numerical index
df_reset = combined_series.reset_index()

# Add a new numerical index
df_reset[' '] = range(1, len(df_reset) + 1)

# Set the new numerical index as the index of the DataFrame
df_reset = df_reset.set_index(' ')

df_reset

,level_0,level_1,level_2,level_3,level_4,level_5,0,1,2,3,4,5
,,,,,,,,,,,,
1,Sector,Subsector,Category,MSA,County,Year,Population,Total Emissions (MMTCO2e),Emissions per capita (MTCO2e),CO2 Emissions (MMTCO2e),CH4 Emissions (MMTCO2e),N2O Emissions (MMTCO2e)
2,Mobile Combustion,Automobile,Gasoline,New Haven-Milford,New Haven,2021,864751,1.028899,1.189821,1.022483,0.000561,0.005855
3,Mobile Combustion,Automobile,Gasoline,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,1.558471,1.25796,1.548753,0.00085,0.008868
4,Mobile Combustion,Automobile,Gasoline,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,1.062378,1.077086,1.055753,0.00058,0.006045
5,Mobile Combustion,Motorcycle,Gasoline,New Haven-Milford,New Haven,2021,864751,0.036643,0.042374,0.036643,0.0,0.0
6,Mobile Combustion,Motorcycle,Gasoline,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.055503,0.044801,0.055503,0.0,0.0
7,Mobile Combustion,Motorcycle,Gasoline,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.037835,0.038359,0.037835,0.0,0.0
8,Mobile Combustion,Trucks,Diesel,New Haven-Milford,New Haven,2021,864751,1.789613,2.069512,1.788362,0.000097,0.001154
9,Mobile Combustion,Trucks,Diesel,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,2.710721,2.188028,2.708827,0.000147,0.001747
10,Mobile Combustion,Trucks,Diesel,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,1.847843,1.873427,1.846552,0.0001,0.001191
11,Mobile Combustion,Buses,Diesel,New Haven-Milford,New Haven,2021,864751,0.020234,0.023399,0.020193,0.000003,0.000038
12,Mobile Combustion,Buses,Diesel,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.030649,0.024739,0.030586,0.000005,0.000058
13,Mobile Combustion,Buses,Diesel,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.020893,0.021182,0.02085,0.000003,0.000039
14,Electricity Consumption,Residential,Electricity,New Haven-Milford,New Haven,2021,864751,0.612048,0.707773,0.607004,0.002026,0.003018
15,Electricity Consumption,Residential,Electricity,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.875671,0.70682,0.868454,0.002898,0.004318
16,Electricity Consumption,Residential,Electricity,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.86617,0.878162,0.859031,0.002867,0.004272
17,Electricity Consumption,Commercial/Industrial,Electricity,New Haven-Milford,New Haven,2021,864751,0.702893,0.812827,0.6971,0.002326,0.003466
18,Electricity Consumption,Commercial/Industrial,Electricity,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.914548,0.738201,0.907011,0.003027,0.00451
19,Electricity Consumption,Commercial/Industrial,Electricity,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.853478,0.865294,0.846444,0.002825,0.004209
20,Solid Waste Landfills,Landfill fuel combustion,"Distillate Fuel Oil No. 2, Natural Gas, Propane",New Haven-Milford,New Haven,2021,864751,0.0,0.0,,,
21,Solid Waste Landfills,Landfill fuel combustion,"Distillate Fuel Oil No. 2, Natural Gas, Propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.000476,0.000384,,,
22,Solid Waste Landfills,Landfill fuel combustion,"Distillate Fuel Oil No. 2, Natural Gas, Propane",Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.296673,0.30078,,,
23,Solid Waste Landfills,Landfill methane,,New Haven-Milford,New Haven,2021,864751,0.0,0.0,,,
24,Solid Waste Landfills,Landfill methane,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.096186,0.077639,,,
25,Solid Waste Landfills,Landfill methane,,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.0,0.0,,,
26,Stationary Combustion,Residential,"fuel oil, natural gas, propane",New Haven-Milford,New Haven,2020,855733,1.361021,1.590474,1.358261,0.000832,0.001928
27,Stationary Combustion,Residential,"fuel oil, natural gas, propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2020,1231523,2.064354,1.676261,2.059985,0.001318,0.003051
28,Stationary Combustion,Residential,"fuel oil, natural gas, propane",Bridgeport-Stamford-Norwalk,Fairfield,2020,972981,1.492142,1.533578,1.489018,0.000942,0.002181
29,Stationary Combustion,Commercial,"fuel oil, natural gas, propane",New Haven-Milford,New Haven,2020,855733,0.955882,1.117033,,,
30,Stationary Combustion,Commercial,"fuel oil, natural gas, propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2020,1231523,1.600473,1.299589,,,
31,Stationary Combustion,Commercial,"fuel oil, natural gas, propane",Bridgeport-Stamford-Norwalk,Fairfield,2020,972981,0.727635,0.747841,,,
32,Stationary Combustion,Industrial,"fuel oil, natural gas, propane",New Haven-Milford,New Haven,2020,855733,0.339402,0.396621,,,
33,Stationary Combustion,Industrial,"fuel oil, natural gas, propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2020,1231523,0.347809,0.282422,,,
34,Stationary Combustion,Industrial,"fuel oil, natural gas, propane",Bridgeport-Stamford-Norwalk,Fairfield,2020,972981,0.109909,0.112961,,,
35,Agriculture & Land management,Organic fertilizer,Organic,New Haven-Milford,New Haven,2017,862127,0.000099,0.000115,,,
36,Agriculture & Land management,Organic fertilizer,Organic,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2017,1239055,0.000338,0.000273,,,
37,Agriculture & Land management,Organic fertilizer,Organic,Bridgeport-Stamford-Norwalk,Fairfield,2017,976389,0.000107,0.00011,,,
38,Agriculture & Land management,Synthetic fertilizer,Synthetic,New Haven-Milford,New Haven,2017,862127,0.029055,0.033702,,,
39,Agriculture & Land management,Synthetic fertilizer,Synthetic,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2017,1239055,0.165942,0.133926,,,
40,Agriculture & Land management,Synthetic fertilizer,Synthetic,Bridgeport-Stamford-Norwalk,Fairfield,2017,976389,0.013841,0.014175,,,
41,Agriculture & Land management,Manure fertilizer,Manure,New Haven-Milford,New Haven,2017,862127,0.000087,0.000101,,,
42,Agriculture & Land management,Manure fertilizer,Manure,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2017,1239055,0.000638,0.000515,,,
43,Agriculture & Land management,Manure fertilizer,Manure,Bridgeport-Stamford-Norwalk,Fairfield,2017,976389,0.000022,0.000023,,,
44,Wastewater treatment,Wastewater facility,,New Haven-Milford,New Haven,2021,864751,0.092857,0.10738,,,
45,Wastewater treatment,Wastewater facility,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.227553,0.183675,,,
46,Wastewater treatment,Wastewater facility,,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.076608,0.077668,,,
47,Forestry,Deciduous forest,,New Haven-Milford,New Haven,2015,862224,-0.547126,-0.634552,,,
48,Forestry,Deciduous forest,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2015,1240217,-1.570298,-1.266147,,,
49,Forestry,Deciduous forest,,Bridgeport-Stamford-Norwalk,Fairfield,2015,969332,-0.637011,-0.657165,,,
50,Forestry,Coniferous forest,,New Haven-Milford,New Haven,2015,862224,-0.043034,-0.049911,,,
51,Forestry,Coniferous forest,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2015,1240217,-0.288634,-0.232728,,,
52,Forestry,Coniferous forest,,Bridgeport-Stamford-Norwalk,Fairfield,2015,969332,-0.060556,-0.062472,,,
53,Forestry,Forested wetland,,New Haven-Milford,New Haven,2015,862224,-0.037731,-0.04376,,,
54,Forestry,Forested wetland,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2015,1240217,-0.124816,-0.10064,,,
55,Forestry,Forested wetland,,Bridgeport-Stamford-Norwalk,Fairfield,2015,969332,-0.039664,-0.040919,,,

In [68]:
# Set the first row as the column index
df_reset.columns = df_reset.iloc[0]

# Drop the first row (which is now the column index)
df_reset = df_reset.drop(df_reset.index[0])
df_reset = df_reset.reset_index(drop=True)
df_reset

1,Sector,Subsector,Category,MSA,County,Year,Population,Total Emissions (MMTCO2e),Emissions per capita (MTCO2e),CO2 Emissions (MMTCO2e),CH4 Emissions (MMTCO2e),N2O Emissions (MMTCO2e)
0,Mobile Combustion,Automobile,Gasoline,New Haven-Milford,New Haven,2021,864751,1.028899,1.189821,1.022483,0.000561,0.005855
1,Mobile Combustion,Automobile,Gasoline,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,1.558471,1.25796,1.548753,0.00085,0.008868
2,Mobile Combustion,Automobile,Gasoline,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,1.062378,1.077086,1.055753,0.00058,0.006045
3,Mobile Combustion,Motorcycle,Gasoline,New Haven-Milford,New Haven,2021,864751,0.036643,0.042374,0.036643,0.0,0.0
4,Mobile Combustion,Motorcycle,Gasoline,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.055503,0.044801,0.055503,0.0,0.0
5,Mobile Combustion,Motorcycle,Gasoline,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.037835,0.038359,0.037835,0.0,0.0
6,Mobile Combustion,Trucks,Diesel,New Haven-Milford,New Haven,2021,864751,1.789613,2.069512,1.788362,0.000097,0.001154
7,Mobile Combustion,Trucks,Diesel,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,2.710721,2.188028,2.708827,0.000147,0.001747
8,Mobile Combustion,Trucks,Diesel,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,1.847843,1.873427,1.846552,0.0001,0.001191
9,Mobile Combustion,Buses,Diesel,New Haven-Milford,New Haven,2021,864751,0.020234,0.023399,0.020193,0.000003,0.000038
10,Mobile Combustion,Buses,Diesel,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.030649,0.024739,0.030586,0.000005,0.000058
11,Mobile Combustion,Buses,Diesel,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.020893,0.021182,0.02085,0.000003,0.000039
12,Electricity Consumption,Residential,Electricity,New Haven-Milford,New Haven,2021,864751,0.612048,0.707773,0.607004,0.002026,0.003018
13,Electricity Consumption,Residential,Electricity,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.875671,0.70682,0.868454,0.002898,0.004318
14,Electricity Consumption,Residential,Electricity,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.86617,0.878162,0.859031,0.002867,0.004272
15,Electricity Consumption,Commercial/Industrial,Electricity,New Haven-Milford,New Haven,2021,864751,0.702893,0.812827,0.6971,0.002326,0.003466
16,Electricity Consumption,Commercial/Industrial,Electricity,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.914548,0.738201,0.907011,0.003027,0.00451
17,Electricity Consumption,Commercial/Industrial,Electricity,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.853478,0.865294,0.846444,0.002825,0.004209
18,Solid Waste Landfills,Landfill fuel combustion,"Distillate Fuel Oil No. 2, Natural Gas, Propane",New Haven-Milford,New Haven,2021,864751,0.0,0.0,,,
19,Solid Waste Landfills,Landfill fuel combustion,"Distillate Fuel Oil No. 2, Natural Gas, Propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.000476,0.000384,,,
20,Solid Waste Landfills,Landfill fuel combustion,"Distillate Fuel Oil No. 2, Natural Gas, Propane",Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.296673,0.30078,,,
21,Solid Waste Landfills,Landfill methane,,New Haven-Milford,New Haven,2021,864751,0.0,0.0,,,
22,Solid Waste Landfills,Landfill methane,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.096186,0.077639,,,
23,Solid Waste Landfills,Landfill methane,,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.0,0.0,,,
24,Stationary Combustion,Residential,"fuel oil, natural gas, propane",New Haven-Milford,New Haven,2020,855733,1.361021,1.590474,1.358261,0.000832,0.001928
25,Stationary Combustion,Residential,"fuel oil, natural gas, propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2020,1231523,2.064354,1.676261,2.059985,0.001318,0.003051
26,Stationary Combustion,Residential,"fuel oil, natural gas, propane",Bridgeport-Stamford-Norwalk,Fairfield,2020,972981,1.492142,1.533578,1.489018,0.000942,0.002181
27,Stationary Combustion,Commercial,"fuel oil, natural gas, propane",New Haven-Milford,New Haven,2020,855733,0.955882,1.117033,,,
28,Stationary Combustion,Commercial,"fuel oil, natural gas, propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2020,1231523,1.600473,1.299589,,,
29,Stationary Combustion,Commercial,"fuel oil, natural gas, propane",Bridgeport-Stamford-Norwalk,Fairfield,2020,972981,0.727635,0.747841,,,
30,Stationary Combustion,Industrial,"fuel oil, natural gas, propane",New Haven-Milford,New Haven,2020,855733,0.339402,0.396621,,,
31,Stationary Combustion,Industrial,"fuel oil, natural gas, propane",Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2020,1231523,0.347809,0.282422,,,
32,Stationary Combustion,Industrial,"fuel oil, natural gas, propane",Bridgeport-Stamford-Norwalk,Fairfield,2020,972981,0.109909,0.112961,,,
33,Agriculture & Land management,Organic fertilizer,Organic,New Haven-Milford,New Haven,2017,862127,0.000099,0.000115,,,
34,Agriculture & Land management,Organic fertilizer,Organic,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2017,1239055,0.000338,0.000273,,,
35,Agriculture & Land management,Organic fertilizer,Organic,Bridgeport-Stamford-Norwalk,Fairfield,2017,976389,0.000107,0.00011,,,
36,Agriculture & Land management,Synthetic fertilizer,Synthetic,New Haven-Milford,New Haven,2017,862127,0.029055,0.033702,,,
37,Agriculture & Land management,Synthetic fertilizer,Synthetic,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2017,1239055,0.165942,0.133926,,,
38,Agriculture & Land management,Synthetic fertilizer,Synthetic,Bridgeport-Stamford-Norwalk,Fairfield,2017,976389,0.013841,0.014175,,,
39,Agriculture & Land management,Manure fertilizer,Manure,New Haven-Milford,New Haven,2017,862127,0.000087,0.000101,,,
40,Agriculture & Land management,Manure fertilizer,Manure,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2017,1239055,0.000638,0.000515,,,
41,Agriculture & Land management,Manure fertilizer,Manure,Bridgeport-Stamford-Norwalk,Fairfield,2017,976389,0.000022,0.000023,,,
42,Wastewater treatment,Wastewater facility,,New Haven-Milford,New Haven,2021,864751,0.092857,0.10738,,,
43,Wastewater treatment,Wastewater facility,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2021,1238888,0.227553,0.183675,,,
44,Wastewater treatment,Wastewater facility,,Bridgeport-Stamford-Norwalk,Fairfield,2021,986344,0.076608,0.077668,,,
45,Forestry,Deciduous forest,,New Haven-Milford,New Haven,2015,862224,-0.547126,-0.634552,,,
46,Forestry,Deciduous forest,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2015,1240217,-1.570298,-1.266147,,,
47,Forestry,Deciduous forest,,Bridgeport-Stamford-Norwalk,Fairfield,2015,969332,-0.637011,-0.657165,,,
48,Forestry,Coniferous forest,,New Haven-Milford,New Haven,2015,862224,-0.043034,-0.049911,,,
49,Forestry,Coniferous forest,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2015,1240217,-0.288634,-0.232728,,,
50,Forestry,Coniferous forest,,Bridgeport-Stamford-Norwalk,Fairfield,2015,969332,-0.060556,-0.062472,,,
51,Forestry,Forested wetland,,New Haven-Milford,New Haven,2015,862224,-0.037731,-0.04376,,,
52,Forestry,Forested wetland,,Hartford-east Hartford-Middletown,"Hartford, Middlesex, Tolland",2015,1240217,-0.124816,-0.10064,,,
53,Forestry,Forested wetland,,Bridgeport-Stamford-Norwalk,Fairfield,2015,969332,-0.039664,-0.040919,,,

In [71]:
df_reset.to_csv('C:/Users/peiyaozhao/NARS Dropbox/Projects/CT-GHG-Inventories/Results/Automated-Emissions-Summary.csv')

In [72]:
df_reset.to_csv('../../../results/Automated-Emissions-Summary.csv')