In [5]:
# import all data manipulation libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd


# emmision data
emission_data = pd.read_csv('../../results/Activity-Emissions-Summary.csv')
Hartford_east_Hartford_Middletown  = gpd.read_file('QGIS-processed- shapefile/Hartford-east Hartford-Middletown MSA.shp')
Connecticut = gpd.read_file('QGIS-processed- shapefile/Connecticut.shp')
Hartford_City = gpd.read_file('QGIS-processed- shapefile/Hartford City.shp')
Bridgeport_Stamford_Norwalk_MSA = gpd.read_file('QGIS-processed- shapefile/Bridgeport-Stamford-Norwalk MSA.shp')
New_Haven_City = gpd.read_file('QGIS-processed- shapefile/New Haven City.shp')
# New Haven-Milford MSA
New_Haven_Milford_MSA = gpd.read_file('QGIS-processed- shapefile/New Haven-Milford MSA.shp')
# Waterbury City
Waterbury_City = gpd.read_file('QGIS-processed- shapefile/Waterbury City.shp')

# for all shapefiles, convert column name NAME10 to NAME
for shapefile in [Hartford_east_Hartford_Middletown, Connecticut, Hartford_City, Bridgeport_Stamford_Norwalk_MSA, New_Haven_City, New_Haven_Milford_MSA, Waterbury_City]:
    shapefile.rename(columns={'NAME10':'NAME'}, inplace=True)

# concatenate all the shapefiles
# this line shows all county lines in the shapefiles but we only need the ones in the next line
# counties_shapefile = pd.concat([Hartford_east_Hartford_Middletown, Connecticut, Hartford_City, Bridgeport_Stamford_Norwalk_MSA, New_Haven_City, New_Haven_Milford_MSA, Waterbury_City], ignore_index=True)

counties_shapefile = pd.concat([Hartford_east_Hartford_Middletown, Connecticut, Bridgeport_Stamford_Norwalk_MSA, New_Haven_Milford_MSA], ignore_index=True)
# rename column "New Haven-Milford" to "New Haven", "Hartford-West Hartford-East Hartford" to "Hartford, Middlesex, Tolland", "Bridgeport-Stamford-Norwalk" to "Fairfield"
counties_shapefile['NAME'] = counties_shapefile['NAME'].str.replace('New Haven-Milford', 'New Haven')
counties_shapefile['NAME'] = counties_shapefile['NAME'].str.replace('Hartford-West Hartford-East Hartford', 'Hartford, Middlesex, Tolland')
counties_shapefile['NAME'] = counties_shapefile['NAME'].str.replace('Bridgeport-Stamford-Norwalk', 'Fairfield')


# remove ", CT" from the NAME column
counties_shapefile['NAME'] = counties_shapefile['NAME'].str.replace(', CT', '')

# convert counties_shapefile to csv and save in same directory
counties_shapefile.to_csv('county_shapefile.csv')

# add a row to the emission data that contains the County ENTRY "Connecticut"
new_row = pd.DataFrame({'County':'Connecticut'}, index=[0])

# concatenate the new row to the emission data
emission_data = pd.concat([new_row, emission_data], ignore_index=True)


display(emission_data.head(10))
display(emission_data.County.unique())
print(emission_data.shape)

display(counties_shapefile.head(10))
print(counties_shapefile.shape)

,County,MSA,Year,Sector,Subsector,Activity Data Description,Activity Data Unit,Activity Data,GHG Emissions (MMTCO2e),Population,Emissions per Capita (MTCO2e)
0,Connecticut,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,New Haven,New Haven-Milford,2021.0,Mobile Combustion,Automobile,Vehicle Miles Traveled,Billion Miles,2.806589,1.028899,864751.0,1.189821
2,"Hartford, Middlesex, Tolland",Hartford-east Hartford-Middletown,2021.0,Mobile Combustion,Automobile,Vehicle Miles Traveled,Billion Miles,4.251133,1.558471,1238888.0,1.257960
3,Fairfield,Bridgeport-Stamford-Norwalk,2021.0,Mobile Combustion,Automobile,Vehicle Miles Traveled,Billion Miles,2.897910,1.062378,986344.0,1.077086
4,New Haven,New Haven-Milford,2021.0,Mobile Combustion,Motorcycle,Vehicle Miles Traveled,Billion Miles,0.208674,0.036643,864751.0,0.042374
5,"Hartford, Middlesex, Tolland",Hartford-east Hartford-Middletown,2021.0,Mobile Combustion,Motorcycle,Vehicle Miles Traveled,Billion Miles,0.316078,0.055503,1238888.0,0.044801
6,Fairfield,Bridgeport-Stamford-Norwalk,2021.0,Mobile Combustion,Motorcycle,Vehicle Miles Traveled,Billion Miles,0.215464,0.037835,986344.0,0.038359
7,New Haven,New Haven-Milford,2021.0,Mobile Combustion,Trucks,Vehicle Miles Traveled,Billion Miles,3.870990,1.789613,864751.0,2.069512
8,"Hartford, Middlesex, Tolland",Hartford-east Hartford-Middletown,2021.0,Mobile Combustion,Trucks,Vehicle Miles Traveled,Billion Miles,5.863378,2.710721,1238888.0,2.188028
9,Fairfield,Bridgeport-Stamford-Norwalk,2021.0,Mobile Combustion,Trucks,Vehicle Miles Traveled,Billion Miles,3.996944,1.847843,986344.0,1.873427

array(['Connecticut', 'New Haven', 'Hartford, Middlesex, Tolland',
       'Fairfield'], dtype=object)

(61, 11)

,fid,CSAFP,CBSAFP,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry,STATEFP,STATENS,STUSPS
0,272.0,278,25540,310M400US25540,25540,"Hartford, Middlesex, Tolland",M1,3.922845e+09,2.387726e+08,"POLYGON ((-73.02054 42.00009, -73.00876 42.038...",NaN,NaN,NaN
1,NaN,NaN,NaN,0400000US09,09,Connecticut,00,1.254250e+10,1.815618e+09,"MULTIPOLYGON (((-72.76143 41.24233, -72.75973 ...",09,01779780,CT
2,NaN,408,14860,310M400US14860,14860,Fairfield,M1,1.618651e+09,5.492935e+08,"MULTIPOLYGON (((-73.21717 41.14391, -73.21611 ...",NaN,NaN,NaN
3,782.0,408,35300,310M400US35300,35300,New Haven,M1,1.565688e+09,6.670812e+08,"MULTIPOLYGON (((-72.76143 41.24233, -72.75973 ...",NaN,NaN,NaN

(4, 13)

In [36]:
# import json
# from shapely.geometry import shape, Polygon, MultiPolygon
# from shapely.geometry import shape

# data_with_counties = pd.merge(emission_data, counties_shapefile, left_on='County', right_on='NAME')
# data_with_counties['geometry_geojson'] = data_with_counties['geometry'].apply(lambda x: x.__geo_interface__)
# # apply df['geometry'] = df['geojson_str'].apply(lambda x: shape(json.loads(x)))
# # data_with_counties['geometry_geojson'] = data_with_counties['geometry_geojson'].apply(lambda x: shape (json.loads(x)))
# # data_with_counties['geometry_shapely'] = data_with_counties['geometry_geojson'].apply(lambda x: shape(x))
# data_with_counties['geometry_geojson_str'] = data_with_counties['geometry_geojson'].apply(lambda x: json.dumps(x))


# # Transforming the 'geometry_geojson_str' to a complete GeoJSON object
# def wrap_geojson(geometry_str):
#     # Convert the geometry string back to a dictionary
#     geometry_dict = json.loads(geometry_str)
    
#     # Wrap the geometry in a full GeoJSON object
#     geojson_full = json.dumps({
#         "type": "Feature",
#         "geometry": geometry_dict,
#         "properties": {}  # Adding an empty properties dictionary, modify as needed
#     })
    
#     return geojson_full

# data_with_counties['complete_geojson'] = data_with_counties['geometry_geojson_str'].apply(wrap_geojson)




# # data_with_msas = pd.merge(emission_data, msas_geo, left_on='MSA', right_on='name_of_msa_column_in_shapefile')
# data_with_counties.head(5)

In [34]:
import pandas as pd
import json
from shapely.geometry import shape, Polygon, MultiPolygon
from shapely.ops import unary_union

# Assuming emission_data and counties_shapefile are already defined and loaded
data_with_counties = pd.merge(emission_data, counties_shapefile, left_on='County', right_on='NAME')

# Convert geometry to GeoJSON
data_with_counties['geometry_geojson'] = data_with_counties['geometry'].apply(lambda x: x.__geo_interface__)


# Simplify MultiPolygons to Polygons by selecting the largest polygon (this is to convert MultiPolygons to Polygons which is the only type of geometry that can be visualized on Superset)
def simplify_multipolygon_to_polygon(geojson):
    geom = shape(geojson)
    if isinstance(geom, MultiPolygon):
        # Convert the MultiPolygon to a list of polygons and select the largest by area
        largest_polygon = max(geom.geoms, key=lambda x: x.area)
        simplified_geojson = largest_polygon.__geo_interface__
    else:
        simplified_geojson = geojson  # No change if not a MultiPolygon
    return simplified_geojson


data_with_counties['simplified_geometry_geojson'] = data_with_counties['geometry_geojson'].apply(simplify_multipolygon_to_polygon)

# Transform the simplified geometry to a complete GeoJSON object
def wrap_geojson(geometry):
    # Ensure the geometry is wrapped as a GeoJSON Feature
    geojson_full = json.dumps({
        "type": "Feature",
        "geometry": geometry,
        "properties": {}  # Empty properties, modify as needed
    })
    return geojson_full

data_with_counties['complete_geojson'] = data_with_counties['simplified_geometry_geojson'].apply(wrap_geojson)

# save to csv
data_with_counties.to_csv('emission_data_with_counties.csv')

# Verify the transformation
data_with_counties[['geometry_geojson', 'complete_geojson']].head()

,geometry_geojson,complete_geojson
0,"{'type': 'MultiPolygon', 'coordinates': [(((-7...","{""type"": ""Feature"", ""geometry"": {""type"": ""Poly..."
1,"{'type': 'MultiPolygon', 'coordinates': [(((-7...","{""type"": ""Feature"", ""geometry"": {""type"": ""Poly..."
2,"{'type': 'Polygon', 'coordinates': (((-73.0205...","{""type"": ""Feature"", ""geometry"": {""type"": ""Poly..."
3,"{'type': 'MultiPolygon', 'coordinates': [(((-7...","{""type"": ""Feature"", ""geometry"": {""type"": ""Poly..."
4,"{'type': 'MultiPolygon', 'coordinates': [(((-7...","{""type"": ""Feature"", ""geometry"": {""type"": ""Poly..."

In [35]:
# save to csv
data_with_counties.to_csv('emission_data_with_counties.csv')

In [5]:
import pydeck as pdk
import pandas as pd

# Sample data: Replace this with your DataFrame
# Assuming your DataFrame 'df' has a column 'geometry_geojson_str' with GeoJSON strings for geometries
data = {
    'name': ['Area 1', 'Area 2'],
    'geometry_geojson_str': [
        '{"type": "Polygon", "coordinates": [[[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]]]}',
        '{"type": "Polygon", "coordinates": [[[15, 5], [25, 35], [5, 35], [-5, 15], [15, 5]]]}'
    ]
}
df = pd.DataFrame(data)

# Convert the GeoJSON string column to a format that PyDeck can interpret
df['geometry'] = df['geometry_geojson_str'].apply(lambda x: eval(x))

# Define a PyDeck layer
# Here, we use the PolygonLayer to plot polygons, but you can use other layers like ScatterplotLayer for points
layer = pdk.Layer(
    'PolygonLayer',  # Change the layer type as needed
    df,
    get_polygon='geometry.coordinates',  # Path to the coordinates
    get_fill_color=[180, 0, 200, 140],  # RGBA color of the polygons
    get_line_color=[0, 0, 0, 200],  # RGBA color of the polygon borders
    get_line_width=2,  # Width of the polygon borders
    pickable=True,
    auto_highlight=True,
)

# Set the viewport location
view_state = pdk.ViewState(latitude=20, longitude=25, zoom=3, bearing=0, pitch=0)

# Render the deck.gl map
r = pdk.Deck(layers=[layer], initial_view_state=view_state, map_style='mapbox://styles/mapbox/light-v9')

# Display the map
r.show()

DeckGLWidget(carto_key=None, custom_libraries=[], google_maps_key=None, json_input='{\n  "initialViewState": {…